use Test::More tests => 26;
BEGIN { use_ok('VSAP::Server::Modules::vsap::config') };

#########################

use Data::Dumper;
use VSAP::Server::Test::Account;

my $user = "joefoo";

## move existing file out of the way
rename("/usr/local/etc/cpx.conf", "/usr/local/etc/cpx.conf.$$")
  if -e "/usr/local/etc/cpx.conf";

my $acctjoefoo = VSAP::Server::Test::Account->create( { username => $user, fullname => 'Joe Foo', password => 'joefoobar', 
	services => 'ftp,mail', clamav => 'y' });
ok( $acctjoefoo->exists(), "joefoo exists");

my $CONFIG_FILE =<<_CONF_;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cpx_config SYSTEM "cpx_config.dtd">
<config>
  <meta>
    <version>1.04</version>
    <warning>Do not edit this file directly</warning>
    <rootbeer>Jones Soda Company</rootbeer>
    <pepper_sauce>Tabasco, McIlhenny Co., Avery Island, La.</pepper_sauce>
    <indian_proverb>Call on God, but row away from the rocks.</indian_proverb>
    <potshot>Micros~1: For when quality, reliability, and security just aren't that important!</potshot>
  </meta>
  <domains>
    <domain>
      <name>horace.com</name>
      <admin>horace</admin>
    </domain>
    <domain>
      <name>farley.com</name>
      <admin>farley</admin>
      <user_limit>0</user_limit>
      <alias_limit>5</alias_limit>
    </domain>
  </domains>
  <users>
    <user name="thursday">
      <domain>thursday.securesites.net</domain>
      <domain_admin/>
      <capabilities>
        <ftp/>
        <shell/>
        <mail/>
      </capabilities>
      <services>
        <ftp/>
        <shell/>
        <mail/>
      </services>
      <fullname>Administrative User</fullname>
      <eu_capabilities/>
    </user>
    <user name="horace">
      <domain>thursday.securesites.net</domain>
      <domain_admin/>
      <capabilities>
        <ftp/>
        <mail/>
      </capabilities>
      <services>
        <ftp/>
        <mail/>
      </services>
      <fullname>Horace Horse</fullname>
      <eu_capabilities/>
    </user>
    <user name="farley">
      <domain>thursday.securesites.net</domain>
      <domain_admin/>
      <capabilities>
        <ftp/>
        <mail/>
        <webmail/>
      </capabilities>
      <services>
        <ftp/>
        <mail/>
        <webmail/>
      </services>
      <fullname>Farley Barley</fullname>
      <eu_capabilities/>
    </user>
    <user name="$user">
      <domain>farley.com</domain>
      <capabilities>
        <mail/>
        <spamassassin/>
        <webmail/>
        <clamav/>
      </capabilities>
      <services>
        <mail/>
        <webmail/>
        <clamav/>
      </services>
      <fullname>Joe Foo</fullname>
    </user>
  </users>
</config>
_CONF_

## make sure this user has clamav or the new object will remove it
VSAP::Server::Modules::vsap::mail::clamav::nv_enable($user);

## create an old-style config file
open CONF, ">/usr/local/etc/cpx.conf"
  or die "Could not write config file: $!\n";
print CONF $CONFIG_FILE;
close CONF;

$co = new VSAP::Server::Modules::vsap::config( username => $user );  ## auto_compat enabled
ok( ! $co->capability('spamassassin') && ! $co->capability('clamav') );
ok( ! $co->service('spamassassin') && ! $co->service('clamav') );

## new elements here
ok(   $co->capability('mail-spamassassin') && $co->capability('mail-clamav'), "has spamassassin capability, has clamav capability");
ok( ! $co->service('mail-spamassassin'), "has no spamassassin service");
ok( $co->service('mail-clamav' ), "has clamav service" );

## check comments
ok( ! $co->comments, "has no comments" );
$co->comments("The quick brown fox jumped over the lazy dog.");
is( $co->comments, "The quick brown fox jumped over the lazy dog." , "comments set correctly");

## version updated
cmp_ok( $co->{dom}->findvalue('/config/meta/version'), ">=", 1.05 );

## turn off clamav for next set of tests
{
    local $> = getpwnam($user);
    VSAP::Server::Modules::vsap::mail::clamav::nv_disable();
}

## create config file again
open CONF, ">/usr/local/etc/cpx.conf";
print CONF $CONFIG_FILE;
close CONF;

## create config object and disable it's refresh
## little test: use undef and 0 separately to test various values of 'false'
$co = new VSAP::Server::Modules::vsap::config(username => $user, auto_refresh => undef, auto_compat => 0);
ok(   $co->capability('spamassassin') &&  $co->capability('clamav') );
ok( ! $co->service('spamassassin') &&  $co->service('clamav') );

## now update the dom
$co->compat;

## old elements gone
ok( ! $co->capability('spamassassin') && ! $co->capability('clamav') );
ok( ! $co->service('spamassassin') && ! $co->service('clamav') );

## new elements here
ok(   $co->capability('mail-spamassassin') && $co->capability('mail-clamav') );
ok( ! $co->service('mail-spamassassin') && $co->service('mail-clamav') );

## now refresh it
$co->refresh;
ok( ! $co->service('mail-spamassassin') );
ok( ! $co->service('mail-clamav') );

## check version
cmp_ok( $co->{dom}->findvalue('/config/meta/version'), ">=", 1.05 );

## remove the config file
unlink '/usr/local/etc/cpx.conf';

## create a conf file with no version node and try again.
open CONF, ">/usr/local/etc/cpx.conf";
print CONF <<_CONF_;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cpx_config SYSTEM "cpx_config.dtd">
<config>
  <meta/>
  <users>
    <user name="$user">
      <domain>farley.com</domain>
      <capabilities>
        <mail/>
        <spamassassin/>
        <webmail/>
        <clamav/>
      </capabilities>
      <services>
        <mail/>
        <webmail/>
        <clamav/>
      </services>
      <fullname>Joe Foo</fullname>
    </user>
  </users>
</config>
_CONF_
close CONF;

## create config file
$co = new VSAP::Server::Modules::vsap::config(username => $user, auto_refresh => 0, auto_compat => 0);
ok(   $co->capability('spamassassin') &&  $co->capability('clamav') );
ok( ! $co->service('spamassassin') &&  $co->service('clamav') );

## now update it
$co->compat;

## old elements gone
ok( ! $co->capability('spamassassin') && ! $co->capability('clamav') );
ok( ! $co->service('spamassassin') && ! $co->service('clamav') );

## new elements here
ok(   $co->capability('mail-spamassassin') && $co->capability('mail-clamav') );
ok( ! $co->service('mail-spamassassin') && $co->service('mail-clamav') );

## check version
cmp_ok( $co->{dom}->findvalue('/config/meta/version'), ">=", 1.05 );


END {
    ## move old file back
    rename("/usr/local/etc/cpx.conf.$$", "/usr/local/etc/cpx.conf")
      if -e "/usr/local/etc/cpx.conf.$$";
}
