use Test::More;
if( $^O eq 'linux' ) { plan skip_all => 'Test irrelevant on Linux'; } else { plan tests => 4; }

BEGIN { use_ok('VSAP::Server::Modules::vsap::config') };

#########################
use_ok('VSAP::Server::Test::Account');
use_ok('POSIX');

my $user1  = 'joefoo';
my $forked = 0;
our $Debug  = 0;
my $Pid    = $$;
my $Children = 3;
my $Child_Tests = 10;
my $Parent_Tests = 15;
my $is_linux=((POSIX::uname())[0] =~ /Linux/) ? 1 : 0;

my @users = map { "misternobody_$_" } (1 .. $Children);

## move existing file out of the way
rename("/usr/local/etc/cpx.conf", "/usr/local/etc/cpx.conf.$$")
  if -e "/usr/local/etc/cpx.conf";

## set up a user w/ mail, ftp
my $acctjoefoo = VSAP::Server::Test::Account->create( { username => 'joefoo', fullname => 'Joe Foo', password => 'joefoobar' });
for my $user ( @users ) {
	my $acctjoefoo = VSAP::Server::Test::Account->create( { username => $user, fullname => 'Joe Foo', password => 'joefoobar' });
}

## make us an SA
$acctjoefoo->make_sa("misternobody_1");

## create a config file
open CONFIG, ">/usr/local/etc/cpx.conf"
  or die "Could not write to cpx.conf: $!\n";
print CONFIG <<_CONFIG_;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cpx_config SYSTEM "cpx_config.dtd">
<config>
  <meta>
    <version>1.06</version>
    <warning>Do not edit this file directly</warning>
    <rootbeer>Jones Soda Company</rootbeer>
    <pepper_sauce>Tabasco, McIlhenny Co., Avery Island, La.</pepper_sauce>
    <indian_proverb>Call on God, but row away from the rocks.</indian_proverb>
    <potshot>Micros~1: For when quality, reliability, and security just aren't that important!</potshot>
  </meta>
  <domains>
    <domain>
      <name>horace.com</name>
      <admin>horace</admin>
    </domain>
    <domain>
      <name>farley.com</name>
      <admin>farley</admin>
      <user_limit>0</user_limit>
      <alias_limit>5</alias_limit>
    </domain>
_CONFIG_

for my $user ( @users ) {
    print CONFIG <<_CONFIG_;
    <domain>
      <name>joefoo-$user.com</name>
      <admin>$user</admin>
    </domain>
_CONFIG_
}

print CONFIG <<_CONFIG_;
  </domains>
_CONFIG_

close CONFIG;

my $test_conf = new VSAP::Server::Modules::vsap::config( username => $user1 );
#print STDERR $test_conf->{dom}->toString(1);
undef $test_conf;

##
## fork until we hit the ceiling
##

## get total procs available
my $top_procs = `sysctl kern.maxproc`; chomp $top_procs;
$top_procs =~ s/^.*:\s*(\d+)/$1/;  ## 150 for a B2

## get current # of procs
my $count = count_procs();  ## e.g., 32 current procs

## fork a bunch of sleepy children, leave room for working children
my %WASTER = ();
fork_wasters( ($top_procs - $Children) - $count );

debug("Finished filling our maxproc limit");
debug("Current procs: " . count_procs());
sleep 1;

## try to recreate race conditions that wipe out the config file
my %CHILDREN = ();

use POSIX 'WNOHANG';
$SIG{CHLD} = sub {
    while( (my $child = waitpid(-1, WNOHANG)) > 0 ) {
	if( delete $CHILDREN{$child} ) {
	    debug("DELETING child pid: $child\n");
	}
    }
};

## fork children
for my $user ( @users ) {
    my $pid = fork();
    unless( defined $pid ) {
	warn "Cannot fork: $!\n";
	next;
    }
    $forked = 1;

    ## child
    unless( $pid ) {
	debug("Child process now working");
	undef $Pid;  ## mark us as a child

	for( my $i = 0; $i < $Child_Tests; $i++ ) {
	    $VSAP::Server::Modules::vsap::config::TRACE = $Debug;
	    my $conf2 = new VSAP::Server::Modules::vsap::config( username => $user );
	    select undef, undef, undef, rand(0.01);

	    if( $i == 0 || $i == 1 ) {
		$conf2->domain("blackpeasoup.tld");
		pwint(1, '');  ## sets text left during harness
		pwint(1, "\U$user\E: " . $conf2->domain);
	    }

	    elsif( $i % 2 ) {
		$conf2->services( fileman => 1, webmail => 0 );
		pwint(1, "\U$user\E: setting services");
	    }

	    elsif( $i % 3 ) {
		$conf2->services( fileman => 0, webmail => 1 );
		pwint(1, "\U$user\E: setting services");
	    }

	    else {
		$conf2->fullname("Barney Hare");
		pwint(1, "\U$user\E: setting fullname");
	    }
	}

	debug("CHILD about to exit");
	exit;
    }

    ## parent in loop
    debug("Parent process now working (created child $pid).");
    $CHILDREN{$pid} = 1;
}


## parent's loop
for( my $i = 0; $i < $Parent_Tests; $i++ ) {
    pwint(0, "Creating a conf object...");
    $VSAP::Server::Modules::vsap::config::TRACE = $Debug;
    my $conf1 = new VSAP::Server::Modules::vsap::config( username => $user1 );
    select undef, undef, undef, rand(0.01);

    ## do some random things
    if( $i == 1 ) {
	pwint(0, "USER1: Setting domain now");
	$conf1->domain("wormsaregoodfood.tld");
    }
    if( $i % 2 ) {
	pwint(0, "USER1: Setting webmail");
	my @users = $conf1->services(webmail => 1);
    }
    elsif( $i % 3 ) {
	pwint(0, "USER1: Setting services");
	$conf1->services( webmail => 0 );
    }
    elsif( $i % 5 ) {
	pwint(0, "USER1: Setting services");
	$conf1->services( webmail => 1 );
    }
    elsif( $i % 7 ) {
	pwint(0, "USER1: Refresh");
	$conf1->refresh;
    }
    elsif( $i % 11 ) {
	pwint(0, "USER1: Changing fullname");
	my %bah = $conf1->fullname("Horsey Sauce");
    }
    elsif( $i % 13 ) {
	pwint(0, "USER1: Changing fullname");
	$conf1->fullname("Horsey Sauce Rocks");
    }
    else {
	pwint(0, "USER1: Unsetting webmail");
	$conf1->services( webmail => 0 );
    }

    if( $i % 3 ) {
#	fork_wasters(1);
    }
}

## wait until the child is done mucking about
while( keys %CHILDREN ) {
    debug("Still have children: " . scalar(keys %CHILDREN));
    my $children = join(',', keys %CHILDREN);
    debug("Parent in END block. Waiting for children ($children)...");
    select undef, undef, undef, 0.5;
}
debug("PARENT about to exit");

my $conf = new VSAP::Server::Modules::vsap::config( username => $user1 );
print STDERR " " x 60, "\r";
my $domain = $conf->domain;
undef $conf;
is( $domain, "wormsaregoodfood.tld", "domain is achieving super shuttle diplomacy" );


kill 15 => keys %WASTER;

END {
    if( $forked ) {
	unless( $Pid ) {
	    debug("Child in END block. Skipping");
	    return;
	}
    }

    getpwnam($user1)    && system qq(vrmuser -y $user1 2>/dev/null);

    for my $user ( @users ) {
	getpwnam($user) && system qq(vrmuser -y $user 2>/dev/null);
    }

    ## move old file back
    rename("/usr/local/etc/cpx.conf.$$", "/usr/local/etc/cpx.conf")
      if -e "/usr/local/etc/cpx.conf.$$";
}

sub debug {
    return unless $Debug;
    my $msg = shift;
    $msg =~ s/\n$//g;
    print STDERR "[$$] $msg\n";
}

sub pwint {
    my $pos = shift;
    my $msg = shift;
    my $nl  = ($Debug ?  "\n" : "\r");
    print STDERR "[$$]:" . ($pos ? " " x 25 . $msg : $msg . " " x 50) . $nl;
}

sub count_procs {
    my $count = 0;
    open PS, "ps -ax|";
    while( <PS> ) { next unless /^\s*\d/; $count++; }
    close PS;
    return $count - 1;  ## our PS pipe has just closed
};

sub fork_wasters {
    my $total = shift;
    for ( my $count = 0; $count < $total; $count++ ) {
	my $pid = fork();

	unless( $pid ) {
	    while( 1 ) { sleep 1; }
	    exit;
	}

	debug("Parent process creating waster child: $pid");
	$WASTER{$pid} = 1;
    }
}
